### PR TITLE
Use Ubuntu 22.04 for CI

### PR DESCRIPTION
**Pull request by kou**
"ubuntu-latest" is "ubuntu-24.04" now.

Our CI worked with "ubuntu-22.04". For example:
https://github.com/facebookincubator/nimble/actions/runs/12754920533

But it doesn't work with "ubuntu-24.04": For example:

https://github.com/facebookincubator/nimble/actions/runs/13042775062/job/36387994477#step:5:694

```text
 [  2%] Building CXX object _deps/abseil-build/absl/time/CMakeFiles/absl_time_zone.dir/internal/cctz/src/time_zone_format.cc.o
In file included from /home/runner/work/nimble/nimble/nimble/_build/release/_deps/abseil-src/absl/time/internal/cctz/src/time_zone_fixed.cc:15:
In file included from /home/runner/work/nimble/nimble/nimble/_build/release/_deps/abseil-src/absl/time/internal/cctz/src/time_zone_fixed.h:18:
In file included from /usr/bin/../lib/gcc/x86_64-linux-gnu/14/../../../../include/c++/14/string:42:
In file included from /usr/bin/../lib/gcc/x86_64-linux-gnu/14/../../../../include/c++/14/bits/char_traits.h:57:
In file included from /usr/bin/../lib/gcc/x86_64-linux-gnu/14/../../../../include/c++/14/bits/stl_construct.h:61:
In file included from /usr/bin/../lib/gcc/x86_64-linux-gnu/14/../../../../include/c++/14/bits/stl_iterator_base_types.h:71:
/usr/bin/../lib/gcc/x86_64-linux-gnu/14/../../../../include/c++/14/bits/iterator_concepts.h:1013:13: error: no matching function for call to '__begin'
        = decltype(ranges::__access::__begin(std::declval<_Tp&>()));
                       ^~~~~~~~~~~~~~~~~~~~~~~~~
```

We should use "ubuntu-24.04" eventually but how about using "ubuntu-22.04" for now for green CI?

### CODE REVIEW

**Comment by kou** [comment]
Could you take a look at this?

**Comment by kou** [comment]
@Yuhta Sorry for bothering you. I'm not sure who to mention here. If you know anyone who can take a look at this PR, please let me know.

**Comment by kou** [comment]
@pedroerp Sorry for bothering you. I'm not sure who to mention here. If you know anyone who can take a look at this PR, please let me know.

**Comment by kou** [comment]
We can use this or #140 to make our CI green.

**Review by pedroerp — APPROVED** [review]
Sorry about the delay on this one, we are still figuring out how structure our team to support this. Thanks @kou

**Comment by kou** [comment]
Thanks!
